/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Dimension;
/*
 * HomeFeed.java
 *
 * Created on 11-22-2011, 06:27:30 PM
 */
/**
 *
 * @author Gary
 */
public class HomeFeed extends javax.swing.JFrame {

    /** Creates new form HomeFeed */
    public HomeFeed() {
        initComponents();
    }
    
    
    
    @Override
    public void setSize(int i, int i1) {

        super.setSize(500,500);
    

    }

    @Override
    public void setBounds(int i, int i1, int i2, int i3) {
        super.setBounds(i, i1, i2, i3);
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogOut2 = new javax.swing.JButton();
        PROFILE = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(690, 574));
        setResizable(false);
        getContentPane().setLayout(null);

        LogOut2.setText("LogOut");
        LogOut2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LogOut2MouseReleased(evt);
            }
        });
        getContentPane().add(LogOut2);
        LogOut2.setBounds(560, 0, 90, 40);

        PROFILE.setText("Perfil");
        PROFILE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PROFILEMouseReleased(evt);
            }
        });
        PROFILE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROFILEActionPerformed(evt);
            }
        });
        getContentPane().add(PROFILE);
        PROFILE.setBounds(490, 0, 67, 40);

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 153));
        jLabel2.setText("FACEBINS 3.0");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 0, 229, 47);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/social-network-1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 742, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PROFILEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROFILEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PROFILEActionPerformed

    private void PROFILEMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILEMouseReleased

        Perfil profile = new Perfil();
        profile.setVisible(true);
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_PROFILEMouseReleased

    private void LogOut2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut2MouseReleased
      
        login lg = new login ();
        lg.setVisible(true); 
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOut2MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new HomeFeed().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOut2;
    private javax.swing.JButton PROFILE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
