
import java.awt.Dimension;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * login.java
 *
 * Created on 11-21-2011, 08:15:10 PM
 */
/**
 *
 * @author Gary
 */
public class login extends javax.swing.JFrame {


    /** Creates new form login */
    public login() {
        initComponents();
    }


    @Override
    public void setSize(int i, int i1) {

        super.setSize(500,500);
    


    }

    

    @Override
    public void setBounds(int i, int i1, int i2, int i3) {
        super.setBounds(i, i1, i2, i3);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        REGI = new javax.swing.JButton();
        LOGIN = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        escritorio.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 153));
        jLabel1.setText("Aun no tienes tu cuenta, registrate es GRATIS");
        jLabel1.setBounds(360, 400, 330, 17);
        escritorio.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        REGI.setText("Registrate");
        REGI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                REGIMouseReleased(evt);
            }
        });
        REGI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGIActionPerformed(evt);
            }
        });
        REGI.setBounds(540, 430, 100, 23);
        escritorio.add(REGI, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LOGIN.setText("Login");
        LOGIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LOGINMouseReleased(evt);
            }
        });
        LOGIN.setBounds(120, 300, 80, 23);
        escritorio.add(LOGIN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPasswordField1.setBounds(110, 240, 105, 20);
        escritorio.add(jPasswordField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField1.setText(" ");
        jTextField1.setBounds(110, 180, 104, 20);
        escritorio.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(51, 255, 153));
        email.setText("Email");
        email.setBounds(40, 180, 40, 17);
        escritorio.add(email, javax.swing.JLayeredPane.DEFAULT_LAYER);

        password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(102, 255, 153));
        password.setText("Password");
        password.setBounds(30, 240, 70, 17);
        escritorio.add(password, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 153));
        jLabel2.setText("FACEBINS 3.0");
        jLabel2.setBounds(20, 0, 310, 80);
        escritorio.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/social-network-1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setBounds(-40, -30, 750, 510);
        escritorio.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void REGIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGIActionPerformed


        // TODO add your handling code here:
    }//GEN-LAST:event_REGIActionPerformed

    private void REGIMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REGIMouseReleased

        Registro reg = new Registro();
        
        reg.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_REGIMouseReleased

    private void LOGINMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGINMouseReleased
        HomeFeed hf = new HomeFeed();
        hf.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGINMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LOGIN;
    private javax.swing.JButton REGI;
    private javax.swing.JLabel email;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel password;
    // End of variables declaration//GEN-END:variables


}
